### ISSUE TITLE
Support Maple on Cloudron: One-click maple deployment

### ISSUE THREAD

**Issue by OrcVole** [gemrest/maple#1]
Gemini and maple are simple, but deploment is complex. Make it easy by supporting Maple on Cloudron. Most of the hard work (creation of a Docker image) has already been completed. Maple has been requested here, and you are invited to participate in the thread and introduce yourselves:

https://forum.cloudron.io/topic/7823/maple-on-cloudon-gemini-server?_=1666158979496

There is a live demo, where you can see how easy it is to deploy web-facing tools on the Cloudron website. It is worth a look:

http://cloudron.io/

**Comment by Fuwn** [comment]
That's actually pretty cool. I hadn't heard of Cloudron until now and I definitely didn't know about the want for Cloudron support for Maple.

I'll look into seeing how I can get Maple working with Cloudron.

**Comment by Fuwn** [comment]
Upon further research, it looks like Cloudron is designed and limited to host web applications only as https://docs.cloudron.io/security/ states:

> "TCP Security Cloudron blocks all incoming ports except 22 (ssh), 80 (http), 443 (https) When email is enabled, Cloudron allows 25 (SMTP), 587 (MSA/STARTTLS), 465 (MSA/TLS), 993 (IMAPS) and 4190 (WebSieve)".

This avenue seems like a bust.

**Comment by OrcVole** [comment]
Cloudron does have some flexibility with ports, as does Maple. What are Maple's requirements?

https://forum.cloudron.io/post/58951

**Comment by Fuwn** [comment]
As mentioned within the Cloudron thread, 1965 is the only port Maple requires open.

I also took a look at the idea for a web UI and I'm not to sure that it's a great idea. A web UI would completely defeat the purpose of the Gemini protocols ideologies and what it stands for. As well, this entire project is marketed as a minimal server.

**Comment by Fuwn** [comment]
Since both the forum post and this issue seem to be stagnant, I'll go ahead and close this issue.

Like I stated, the idea of a web UI completely goes against both this projects and the Gemini protocols goals. If someone is able to achieve an alternative one-click-deploy option that respects the Gemini protocols goals and principles, they can go ahead and submit a pull request and I'll see about having it integrated.

Until then, for all intents and purposes, the provided Docker and Docker Compose configurations seem like the simpler and most widespread solutions.
