### ISSUE TITLE
Make deployment of Maple easy

### ISSUE THREAD

**Issue by OrcVole** [gemrest/maple#3]
Simplicity is a tenet of the gemini protocol. Unfortunately, deploying a gemini server like Maple is far from simple.

How about creating a .exe and/or an appimage for Maple to help more people setup and run their own gemini servers? 

Every gemini server seems to suffer from this problem.

**Comment by Fuwn** [comment]
Similar discussions of alternative deployment solutions have been discussed previously, see #1.

I'll address a few of your questions and concerns below.

AppImages are meant for desktop applications and are notoriously insecure. This is not a problem for desktop applications, as desktop applications are insecure by nature. AppImages are definitely not ideal for server applications.

Deploying a raw executable is generally discouraged for server applications because of its lack of encapsulation, this is the same issue that AppImages don't solve. Additionally, Maple is written using the POSIX standard libraries, so without an external bridge like MinGW, it doesn't compile natively under Windows. This, and the reasons below, are why I do not provide any distributed executables.

Maple has provided a Docker image from the very start. Docker is widely used as the go-to encapsulation method for both desktop and server applications alike. Docker is simple, and Docker is safe.

As stated in the README of this repository, you can deploy a Maple server in one, very short, command with two spaces if using Docker Compose. You can similarly deploy a Maple server in one command with a few more spaces if using Docker without Docker Compose, maybe spanning three lines if you are being spacious with your line continuation characters.

Of the explored options, there are no simpler solutions than which are already available.
